#!/usr/bin/env node
/* ==========================================================================
   WHILE WE'RE HERE — book compositor.

   Reads content (markdown + json), composes physical pages, and writes:
     build/book.html     the print document (no preview chrome at all)
     build/preview.html  the same pages plus screen-only guides and navigation
     build/geometry.css  print geometry compiled from book.config.js
     prompts/image-manifest.md  regenerated from content/images.json
   ========================================================================== */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';

import { geometry, spineWidth, press } from '../book.config.js';
import * as L from '../src/layouts/index.mjs';
import { esc, page as wrapPage } from '../src/layouts/helpers.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const md = new MarkdownIt({ html: true, typographer: true });
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const json = (p) => JSON.parse(read(p));

/* ---- Geometry ------------------------------------------------------------ */

const LINEN_TEXTURE =
  `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='190' height='190'%3E` +
  `%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.82' numOctaves='3'/%3E` +
  `%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E` +
  `%3Crect width='190' height='190' filter='url(%23n)' opacity='0.055'/%3E%3C/svg%3E")`;

function geometryCss() {
  const g = geometry;
  const mm = (n) => `${n}mm`;
  return `/* GENERATED by scripts/build.mjs from book.config.js — do not edit. */
:root {
  --trim-w: ${mm(g.trimWidth)};
  --trim-h: ${mm(g.trimHeight)};
  --bleed: ${mm(g.bleed)};
  --safe: ${mm(g.safeArea)};
  --crossover: ${mm(g.crossoverGutter)};
  --m-inside: ${mm(g.marginInside)};
  --m-outside: ${mm(g.marginOutside)};
  --m-top: ${mm(g.marginTop)};
  --m-bottom: ${mm(g.marginBottom)};
  --grid-cols: ${g.columns};
  --gutter: ${mm(g.gutter)};
  --baseline: ${mm(g.baseline)};
  --spine-w: ${mm(spineWidth())};
  /* Live bleed only on a press build; a proof is trimmed. */
  --bleed-out: ${press ? mm(g.bleed) : '0mm'};
  --texture-linen: ${LINEN_TEXTURE};
}

@page {
  size: ${mm(g.trimWidth)} ${mm(g.trimHeight)};
  margin: 0;${press ? `\n  bleed: ${mm(g.bleed)};\n  marks: crop cross;` : ''}
}
`;
}

/* ---- Content loading ----------------------------------------------------- */

const BLOCK_RE = /<!--\s*block:\s*([a-z0-9-]+)\s*-->/gi;

function loadDoc(rel) {
  const raw = read(path.join('content', rel));
  const { data, content } = matter(raw);
  const blocks = {};
  const parts = content.split(BLOCK_RE);
  // parts = [preamble, id, body, id, body, ...]
  for (let i = 1; i < parts.length; i += 2) {
    blocks[parts[i]] = md.render(parts[i + 1].trim());
  }
  return { data, html: md.render(parts[0].trim()), blocks };
}

const imagesById = Object.fromEntries(json('content/images.json').images.map((i) => [i.id, i]));
const ctxBase = { root, image: (id) => imagesById[id] };

/* ---- Compositor ---------------------------------------------------------- */
/* Physical page numbering ignores the cover surfaces, as a bound book does.
   A paired spread always begins on a verso; a blank is inserted if the flow
   would land it wrong. Nothing in the layouts needs to know about this. */

function compose(book, toc) {
  const out = [];
  let n = 0;                                  // interior page counter
  const nextSide = () => ((n + 1) % 2 === 1 ? 'recto' : 'verso');

  const emit = (p, { standalone = false, sideOverride = null } = {}) => {
    const side = sideOverride || nextSide();
    if (!standalone) n += 1;
    out.push(wrapPage({
      side,
      folio: p.folio && !standalone ? n : null,
      rubric: p.rubric,
      spread: p.spread,
      label: p.label,
      className: p.cls,
      body: p.html,
    }));
  };

  const emitBlankIfNeeded = (wantSide) => {
    if (nextSide() !== wantSide) {
      emit({ spread: 'blank', folio: false, cls: 'page--blank', label: 'pacing blank', html: '' });
    }
  };

  const place = (result, opts = {}) => {
    if (result.pair) emitBlankIfNeeded('verso');
    else if (opts.prefersRecto) emitBlankIfNeeded('recto');
    result.pages.forEach((p) => emit(p, opts));
  };

  for (const item of book.sequence) {
    switch (item.type) {
      case 'cover-front':
        place(L.coverFront(book), { standalone: true, sideOverride: 'recto' });
        break;
      case 'cover-back':
        place(L.coverBack(book), { standalone: true, sideOverride: 'verso' });
        break;
      case 'blank':
        place(L.blank());
        break;
      case 'half-title':
        place(L.halfTitle(book), { prefersRecto: true });
        break;
      case 'title-spread':
        place(L.titleSpread(book));
        break;
      case 'opening-note':
        place(L.openingNote(loadDoc(item.source)), { prefersRecto: true });
        break;
      case 'contents':
        place(L.contents(book, toc));
        break;
      case 'divider': {
        const { data } = loadDoc(item.source);
        place(L.divider(data, ctxBase));
        break;
      }
      case 'essay': {
        const doc = loadDoc(item.source);
        const essay = doc.data;
        const ctx = { ...ctxBase, blocks: doc.blocks };
        for (const spread of essay.spreads) {
          const key = spread.variant && spread.type === 'reading'
            ? `reading-${spread.variant}`
            : spread.type;
          const renderer = L.essaySpreads[key];
          if (!renderer) throw new Error(`Unknown spread type: ${key}`);
          place(renderer(spread, essay, ctx));
        }
        break;
      }
      default:
        throw new Error(`Unknown sequence item: ${item.type}`);
    }
  }

  return { pages: out, count: n };
}

/* ---- Documents ----------------------------------------------------------- */

const STYLES = ['styles/tokens.css', 'styles/typography.css', 'styles/print.css',
  'styles/layouts.css', 'styles/placeholders.css', 'styles/cover.css'];

function document_({ title, body, preview }) {
  const links = ['geometry.css', ...STYLES]
    .map((h) => `  <link rel="stylesheet" href="${h}">`).join('\n');
  return `<!DOCTYPE html>
<html lang="en"${preview ? '' : ' class="is-book"'}>
<head>
  <meta charset="utf-8">
  <title>${esc(title)}</title>
${links}
${preview ? '  <link rel="stylesheet" href="styles/preview.css">' : ''}
</head>
<body class="${preview ? 'preview is-proof-screen' : 'book'}">
${body}
${preview ? '<script src="scripts/preview.js"></script>' : ''}
</body>
</html>
`;
}

function coverWrapDoc(book) {
  const front = L.coverFront(book).pages[0];
  const back = L.coverBack(book).pages[0];
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Cover wrap — provisional</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<style>
  body { background:#211F1C; display:grid; place-items:center; min-height:100vh; margin:0; padding:60px; }
  .wrap-note { color:#8B8477; font:500 11px/1.6 var(--font-text); letter-spacing:.1em;
               text-transform:uppercase; margin-bottom:24px; text-align:center; }
  .wrap-note b { color:#E4DCC9; }
</style></head>
<body>
<div>
  <p class="wrap-note">Cover wrap &nbsp;·&nbsp; back &nbsp;|&nbsp; spine &nbsp;|&nbsp; front<br>
    Spine <b>${spineWidth()} mm</b> — provisional, from ${geometry.cover.pageCount} pp at
    ${geometry.cover.paperCaliper} mm/leaf. Replace with the printer's template before press.</p>
  <div class="wrap">
    <div class="cover cover-back page--verso">${back.html}</div>
    <div class="spine">
      <div class="spine__stack">
        <p class="spine__text">While We’re Here</p>
        <p class="spine__author">${esc(book.author)}</p>
      </div>
    </div>
    <div class="cover page--recto">${front.html}</div>
    <div class="wrap__fold" style="left: var(--trim-w)"></div>
    <div class="wrap__fold" style="left: calc(var(--trim-w) + var(--spine-w))"></div>
  </div>
</div>
</body></html>
`;
}

function indexDoc(book, count) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(book.title)} — production</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<style>
  html, body { background:#211F1C; }
  body { display:grid; place-items:center; min-height:100vh; margin:0; padding:60px 24px; }
  .hub { width:min(560px, 100%); color:#C9C1B0; font-family:var(--font-text); }
  .hub h1 { font-family:var(--font-display); font-size:44px; line-height:1; color:#F0E9D9;
            margin:0 0 6px; letter-spacing:-.02em; font-weight:400; }
  .hub p.sub { font-size:12px; letter-spacing:.16em; text-transform:uppercase; color:#7C766A; margin:0 0 40px; }
  .hub a { display:flex; justify-content:space-between; align-items:baseline; gap:16px;
           padding:16px 0; border-top:1px solid #35322C; color:#C9C1B0; text-decoration:none; }
  .hub a:last-of-type { border-bottom:1px solid #35322C; }
  .hub a:hover { color:#F0E9D9; }
  .hub a b { font-weight:500; font-size:15px; }
  .hub a span { font-size:11px; letter-spacing:.12em; text-transform:uppercase; color:#7C766A; text-align:right; }
  .hub footer { margin-top:36px; font-size:11px; line-height:1.7; color:#5E594F; }
  .hub footer b { color:#8B8477; font-weight:500; }
</style></head>
<body><div class="hub">
  <h1>While We’re Here</h1>
  <p class="sub">${esc(book.author)} &nbsp;·&nbsp; prototype</p>
  <a href="preview.html"><b>Spread preview</b><span>${count} pp &nbsp;·&nbsp; guides &amp; navigation</span></a>
  <a href="book.html"><b>Print document</b><span>raw pages &nbsp;·&nbsp; no chrome</span></a>
  <a href="cover-wrap.html"><b>Cover wrap</b><span>back | spine | front</span></a>
  <footer>
    ${geometry.trimWidth} × ${geometry.trimHeight} mm trim &nbsp;·&nbsp; ${geometry.bleed} mm bleed
    &nbsp;·&nbsp; spine <b>${spineWidth()} mm</b> provisional.<br>
    Printer geometry is not final. Everything comes from <b>book.config.js</b>.
  </footer>
</div></body></html>
`;
}

/* ---- Image manifest ------------------------------------------------------ */

function writeManifest() {
  const { images } = json('content/images.json');
  const row = (i) => [
    i.id, i.essay, i.section, i.spread, i.kind, i.subject, i.concept, i.purpose,
    i.aspect, i.target, i.filename, i.status, i.selection, i.revision || '—',
  ].map((c) => String(c).replace(/\|/g, '\\|')).join(' | ');

  const body = `<!-- GENERATED from content/images.json by \`npm run build\`. Edit the JSON, not this file. -->

# Image manifest

One row per planned image. Status moves \`not generated\` → \`generated\` → \`selected\`.
A file dropped into \`public/images/<kind>/<filename>\` replaces its placeholder plate on
the next build, so the proof PDF always shows exactly what has and has not been made.

| ID | Essay | Section | Spread | Type | Subject | Concept | Narrative purpose | Aspect | Target | Filename | Status | Selected | Revision notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${images.map((i) => `| ${row(i)} |`).join('\n')}

## Resolution rules

- Full single-page image: **4000 × 4000 px** minimum at 300 × 300 mm trim.
- Full two-page spread: **8000 × 4000 px** minimum.
- Always keep the largest clean original. Never upscale a weak generation to hit a number.
- Any full-bleed image must carry ${geometry.bleed} mm of expendable material on every trimmed edge.
`;
  fs.writeFileSync(path.join(root, 'prompts/image-manifest.md'), body);
}

/* ---- Assets -------------------------------------------------------------- */

function copyDir(from, to) {
  if (!fs.existsSync(from)) return;
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

/* ---- Build --------------------------------------------------------------- */

export function build() {
  const book = json('content/book.json');
  const toc = json('content/contents.json');
  const out = path.join(root, 'build');

  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, 'geometry.css'), geometryCss());
  copyDir(path.join(root, 'src/styles'), path.join(out, 'styles'));
  copyDir(path.join(root, 'src/scripts'), path.join(out, 'scripts'));
  copyDir(path.join(root, 'public'), out);

  const { pages, count } = compose(book, toc);
  const body = pages.join('\n');

  fs.writeFileSync(path.join(out, 'book.html'),
    document_({ title: `${book.title} — ${book.author}`, body, preview: false }));
  fs.writeFileSync(path.join(out, 'preview.html'),
    document_({ title: `${book.title} — preview`, body, preview: true }));
  fs.writeFileSync(path.join(out, 'cover-wrap.html'), coverWrapDoc(book));
  fs.writeFileSync(path.join(out, 'index.html'), indexDoc(book, count));
  writeManifest();

  const sheets = Math.ceil(count / 2);
  console.log(
    `✓ ${count} interior pages (${sheets} leaves) + 2 cover surfaces` +
    `  ·  ${press ? 'PRESS: bleed + crop marks' : 'proof: trimmed, no marks'}` +
    `  ·  spine ${spineWidth()} mm (provisional)`
  );
}

build();

if (process.argv.includes('--watch')) {
  const { default: chokidar } = await import('chokidar');
  chokidar
    .watch(['content', 'src', 'public', 'book.config.js'], { cwd: root, ignoreInitial: true })
    .on('all', () => {
      try { build(); } catch (e) { console.error('✗', e.message); }
    });
  console.log('watching content/ src/ public/ …');
}
