#!/usr/bin/env node
/* ==========================================================================
   WHILE WE'RE HERE — book compositor.

   Reads content (markdown + json), composes physical pages, and writes:
     build/book.html     the print document (no preview chrome at all)
     build/preview.html  the same pages plus screen-only guides and navigation
     build/geometry.css  print geometry compiled from book.config.js
     prompts/image-manifest.md  regenerated from content/images.json
   ========================================================================== */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';

import { geometry, spineWidth, press, web } from '../book.config.js';
import * as L from '../src/layouts/index.mjs';
import { esc, page as wrapPage } from '../src/layouts/helpers.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const md = new MarkdownIt({ html: true, typographer: true });
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const json = (p) => JSON.parse(read(p));

/* ---- Geometry ------------------------------------------------------------ */

const LINEN_TEXTURE =
  `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='190' height='190'%3E` +
  `%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.82' numOctaves='3'/%3E` +
  `%3CfeColorMatrix type='saturate' values='0'/%3E%3C/filter%3E` +
  `%3Crect width='190' height='190' filter='url(%23n)' opacity='0.055'/%3E%3C/svg%3E")`;

function geometryCss() {
  const g = geometry;
  const mm = (n) => `${n}mm`;
  return `/* GENERATED by scripts/build.mjs from book.config.js — do not edit. */
:root {
  --trim-w: ${mm(g.trimWidth)};
  --trim-h: ${mm(g.trimHeight)};
  --bleed: ${mm(g.bleed)};
  --safe: ${mm(g.safeArea)};
  --crossover: ${mm(g.crossoverGutter)};
  --m-inside: ${mm(g.marginInside)};
  --m-outside: ${mm(g.marginOutside)};
  --m-top: ${mm(g.marginTop)};
  --m-bottom: ${mm(g.marginBottom)};
  --grid-cols: ${g.columns};
  --gutter: ${mm(g.gutter)};
  --baseline: ${mm(g.baseline)};
  --spine-w: ${mm(spineWidth())};
  /* Live bleed only on a press build; a proof is trimmed. */
  --bleed-out: ${press ? mm(g.bleed) : '0mm'};
  --texture-linen: ${LINEN_TEXTURE};
}

@page {
  size: ${mm(g.trimWidth)} ${mm(g.trimHeight)};
  margin: 0;${press ? `\n  bleed: ${mm(g.bleed)};\n  marks: crop cross;` : ''}
}
`;
}

/* ---- Content loading ----------------------------------------------------- */

const BLOCK_RE = /<!--\s*block:\s*([a-z0-9-]+)\s*-->/gi;

/**
 * Bind the last two words of every paragraph with a non-breaking space, so no
 * line ends up carrying a single word. This is the typesetter's fix, applied at
 * build time rather than by editing the prose — it survives copy edits and it
 * cannot be forgotten on the essay nobody re-read.
 *
 * `text-wrap: pretty` is set as well, but it is a hint the engine may decline;
 * this is not. Stanza lines (separated by <br>) are handled individually, and a
 * segment of one or two words is left alone because there is nothing to bind.
 */
function bindWidows(html) {
  const bind = (seg) => {
    const words = seg.trimEnd().split(/(\s+)/);
    if (words.filter((w) => w.trim()).length < 3) return seg;
    for (let i = words.length - 1; i > 0; i--) {
      if (/^\s+$/.test(words[i]) && words[i + 1] && words[i + 1].trim()) {
        words[i] = '\u00A0';
        return words.join('') + seg.slice(seg.trimEnd().length);
      }
    }
    return seg;
  };
  return html.replace(/<p([^>]*)>([\s\S]*?)<\/p>/g, (all, attrs, inner) =>
    `<p${attrs}>${inner.split(/(<br\s*\/?>)/).map((s) => (s.startsWith('<br') ? s : bind(s))).join('')}</p>`);
}

function loadDoc(rel) {
  const raw = read(path.join('content', rel));
  const { data, content } = matter(raw);
  const blocks = {};
  const parts = content.split(BLOCK_RE);
  // parts = [preamble, id, body, id, body, ...]
  for (let i = 1; i < parts.length; i += 2) {
    blocks[parts[i]] = bindWidows(md.render(parts[i + 1].trim()));
  }
  return { data, html: bindWidows(md.render(parts[0].trim())), blocks };
}

const imagesById = Object.fromEntries(json('content/images.json').images.map((i) => [i.id, i]));
const ctxBase = { root, image: (id) => imagesById[id] };

/* ---- Compositor ---------------------------------------------------------- */
/* Physical page numbering ignores the cover surfaces, as a bound book does.
   A paired spread always begins on a verso; a blank is inserted if the flow
   would land it wrong. Nothing in the layouts needs to know about this. */

function compose(book, toc, folios = {}) {
  const out = [];
  const openings = {};                        // essay title -> folio of its title page
  /* The reproduced records are one exhibit returning, and the pages say so —
     "Record 1 of 3" — with both numbers derived here, never typed, for the same
     reason the contents page derives its counts: re-pacing the book must not be
     able to leave a page lying. */
  let recordTotal = 0;
  for (const item of book.sequence) {
    if (item.type !== 'essay') continue;
    const { data } = loadDoc(item.source);
    for (const sp of data.spreads || []) if (sp.record) recordTotal += 1;
  }
  let recordN = 0;
  let n = 0;                                  // interior page counter
  let stage = 1;                              // observe → notice → understand → expand → integrate
  const nextSide = () => ((n + 1) % 2 === 1 ? 'recto' : 'verso');

  const emit = (p, { standalone = false, sideOverride = null } = {}) => {
    const side = sideOverride || nextSide();
    if (!standalone) n += 1;
    out.push(wrapPage({
      side,
      folio: p.folio && !standalone ? n : null,
      rubric: p.rubric,
      spread: p.spread,
      label: p.label,
      className: `stage-${stage} ${p.cls}`,
      body: p.html,
    }));
  };

  const emitBlankIfNeeded = (wantSide) => {
    if (nextSide() !== wantSide) {
      emit({ spread: 'blank', folio: false, cls: 'page--blank', label: 'pacing blank', html: '' });
    }
  };

  const place = (result, opts = {}) => {
    if (result.pair) emitBlankIfNeeded('verso');
    else if (opts.prefersRecto) emitBlankIfNeeded('recto');
    result.pages.forEach((p) => emit(p, opts));
  };

  for (const item of book.sequence) {
    switch (item.type) {
      case 'cover-front':
        place(L.coverFront(book, ctxBase), { standalone: true, sideOverride: 'recto' });
        break;
      case 'cover-back':
        place(L.coverBack(book, ctxBase), { standalone: true, sideOverride: 'verso' });
        break;
      case 'blank':
        place(L.blank());
        break;
      case 'handed-over':
        place(L.handedOver(item, ctxBase));
        break;
      case 'dedication':
        place(L.dedication(book));
        break;
      case 'half-title':
        place(L.halfTitle(book), { prefersRecto: true });
        break;
      case 'title-spread':
        place(L.titleSpread(book, Object.values(imagesById)));
        break;
      case 'opening-note':
        place(L.openingNote(loadDoc(item.source)), { prefersRecto: true });
        break;
      case 'contents':
        place(L.contents(book, toc, folios));
        break;
      case 'field-note': {
        const doc = loadDoc(item.source);
        if (doc.data.stage) stage = doc.data.stage;
        place(L.fieldNote({ ...doc.data, html: doc.html }, { ...ctxBase, stage }));
        break;
      }
      case 'divider': {
        const { data } = loadDoc(item.source);
        if (data.stage) stage = data.stage;
        place(L.divider(data, { ...ctxBase, stage }));
        break;
      }
      case 'essay': {
        const doc = loadDoc(item.source);
        const essay = doc.data;
        if (essay.stage) stage = essay.stage;
        const ctx = { ...ctxBase, blocks: doc.blocks, stage };
        openings[L.titleKey(essay.title)] = n + 2;   // opener is a pair: verso, then the title recto
        for (const spread of essay.spreads) {
          if (spread.record) spread.record.series = `Record ${++recordN} of ${recordTotal}`;
          const variantKey = spread.variant ? `${spread.type}-${spread.variant}` : null;
          const key = variantKey && L.essaySpreads[variantKey] ? variantKey : spread.type;
          const renderer = L.essaySpreads[key];
          if (!renderer) throw new Error(`Unknown spread type: ${key}`);
          place(renderer(spread, essay, ctx));
        }
        break;
      }
      default:
        throw new Error(`Unknown sequence item: ${item.type}`);
    }
  }

  return { pages: out, count: n, openings };
}

/* ---- Documents ----------------------------------------------------------- */

const STYLES = ['fonts.css', 'styles/tokens.css', 'styles/typography.css', 'styles/print.css',
  'styles/layouts.css', 'styles/placeholders.css', 'styles/cover.css'];

function document_({ title, body, preview }) {
  const links = ['geometry.css', ...STYLES]
    .map((h) => `  <link rel="stylesheet" href="${h}">`).join('\n');
  return `<!DOCTYPE html>
<html lang="en"${preview ? '' : ' class="is-book"'}>
<head>
  <meta charset="utf-8">
  <title>${esc(title)}</title>
${links}
${preview ? '  <link rel="stylesheet" href="styles/preview.css">' : ''}
</head>
<body class="${preview ? 'preview is-proof-screen' : 'book'}">
${body}
${preview ? '<script src="scripts/preview.js"></script>' : ''}
</body>
</html>
`;
}

/* All three cover treatments at trim size, for choosing between. */
function coverOptionsDoc(book) {
  const notes = {
    plate: 'Artwork as a specimen inside the page. Quiet, bookish — and the one that disappears on a shelf.',
    bleed: 'Artwork edge to edge, title running off the trim. One colour and one word at two metres.',
    window: 'Artwork only inside the letterforms. The title becomes the aperture onto the systems.',
    orb: 'The artwork as one circle, title over its upper limb. Shown with the square plate clipped — the real circular artwork is still to be made.',
  };
  const pages = Object.keys(L.coverVariants).map((v) => {
    const p = L.coverFront(book, ctxBase, v).pages[0];
    return `<section class="page page--recto stage-1 ${p.cls}" data-side="recto"
              data-spread="cover · ${v}" data-label="${v}">${p.html}</section>`;
  });
  /* Two documents from one set of pages, for the same reason the book has two:
     the screen version carries the preview chrome, and the print version
     carries none of it. PDF-ing the screen page emitted a fifth sheet from the
     preview body's own padding. */
  const doc = (preview) => `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Cover options — ${esc(book.title)}</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
${preview ? '<link rel="stylesheet" href="styles/preview.css">' : ''}
<style>
  /* Inside the page, not above it: a label sitting outside the page box makes
     the paginator emit an extra sheet for the overflow. */
  .cover-note { position:absolute; left:0; right:0; bottom:0; z-index:9;
    padding:4mm 6mm; background:rgba(20,19,17,.88); color:#C9C1B0;
    font:400 8pt/1.5 var(--font-note); letter-spacing:.04em; }
  .cover-note b { color:#F0E9D9; text-transform:uppercase; letter-spacing:.16em; }
</style></head>
<body class="${preview ? 'preview is-proof-screen' : 'book'}">
${pages.join('\n')}
<script>
  document.querySelectorAll('.page').forEach((p) => {
    const n = document.createElement('div');
    n.className = 'cover-note';
    n.innerHTML = '<b>' + p.dataset.label + '</b> — ' + ${JSON.stringify(notes)}[p.dataset.label];
    p.appendChild(n);
  });
</script>
${preview ? '<script src="scripts/preview.js"></script>' : ''}
</body></html>
`;
  return { screen: doc(true), print: doc(false) };
}

function coverWrapDoc(book) {
  const front = L.coverFront(book, ctxBase).pages[0];
  const back = L.coverBack(book, ctxBase).pages[0];
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Cover wrap — provisional</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<style>
  body { background:#211F1C; display:grid; place-items:center; min-height:100vh; margin:0; padding:60px; }
  .wrap-note { color:#8B8477; font:500 11px/1.6 var(--font-text); letter-spacing:.1em;
               text-transform:uppercase; margin-bottom:24px; text-align:center; }
  .wrap-note b { color:#E4DCC9; }
</style></head>
<body>
<div>
  <p class="wrap-note">Cover wrap &nbsp;·&nbsp; back &nbsp;|&nbsp; spine &nbsp;|&nbsp; front<br>
    Spine <b>${spineWidth()} mm</b> — provisional, from ${geometry.cover.pageCount} pp at
    ${geometry.cover.paperCaliper} mm/leaf. Replace with the printer's template before press.</p>
  <div class="wrap">
    <div class="${back.cls} page--verso">${back.html}</div>
    <div class="spine">
      <div class="spine__stack">
        <p class="spine__text">${esc(book.title).replace(/\u2019/g, '<span class="spine__apos">\u2019</span>')}</p>
        <p class="spine__author">${esc(book.author)}</p>
      </div>
    </div>
    <div class="${front.cls} page--recto">${front.html}</div>
    <div class="wrap__fold" style="left: var(--trim-w)"></div>
    <div class="wrap__fold" style="left: calc(var(--trim-w) + var(--spine-w))"></div>
  </div>
</div>
</body></html>
`;
}

function indexDoc(book, count) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(book.title)} — production</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<style>
  html, body { background:#211F1C; }
  body { display:grid; place-items:center; min-height:100vh; margin:0; padding:60px 24px; }
  .hub { width:min(560px, 100%); color:#C9C1B0; font-family:var(--font-text); }
  .hub h1 { font-family:var(--font-display); font-size:44px; line-height:1; color:#F0E9D9;
            margin:0 0 6px; letter-spacing:-.02em; font-weight:400; }
  .hub p.sub { font-size:12px; letter-spacing:.16em; text-transform:uppercase; color:#7C766A; margin:0 0 40px; }
  .hub a { display:flex; justify-content:space-between; align-items:baseline; gap:16px;
           padding:16px 0; border-top:1px solid #35322C; color:#C9C1B0; text-decoration:none; }
  .hub a:last-of-type { border-bottom:1px solid #35322C; }
  .hub a:hover { color:#F0E9D9; }
  .hub a b { font-weight:500; font-size:15px; }
  .hub a span { font-size:11px; letter-spacing:.12em; text-transform:uppercase; color:#7C766A; text-align:right; }
  .hub footer { margin-top:36px; font-size:11px; line-height:1.7; color:#5E594F; }
  .hub footer b { color:#8B8477; font-weight:500; }
</style></head>
<body><div class="hub">
  <h1>While We’re Here</h1>
  <p class="sub">${esc(book.author)} &nbsp;·&nbsp; prototype</p>
  <a href="preview.html"><b>Spread preview</b><span>${count} pp &nbsp;·&nbsp; guides &amp; navigation</span></a>
  <a href="book.html"><b>Print document</b><span>raw pages &nbsp;·&nbsp; no chrome</span></a>
  <a href="cover-wrap.html"><b>Cover wrap</b><span>back | spine | front</span></a>
  <a href="cover-options.html"><b>Cover options</b><span>three treatments at trim</span></a>
  <a href="direction.html"><b>Art direction</b><span>stages · spectrum · voices</span></a>
  <a href="type.html"><b>Type tester</b><span>candidate stacks at trim size</span></a>
  <footer>
    ${geometry.trimWidth} × ${geometry.trimHeight} mm trim &nbsp;·&nbsp; ${geometry.bleed} mm bleed
    &nbsp;·&nbsp; spine <b>${spineWidth()} mm</b> provisional.<br>
    Printer geometry is not final. Everything comes from <b>book.config.js</b>.
  </footer>
</div></body></html>
`;
}

/* ---- Direction plates ----------------------------------------------------
   The art direction, built at true trim size with the book's own page model,
   so the palette and the type are shown at the scale they will be printed.
   Not part of the book — a working document that happens to be a 12" object. */

const ACTS = [
  { n: 1, name: 'Calm · observational',  ground: 'var(--paper)',      cue: 'Cream paper, soft light, sparse photography, restrained annotation, a great deal of breathing room.' },
  { n: 2, name: 'Discovery · hidden systems', ground: 'var(--bone)',  cue: 'Diagrams, overlays, specimens, cutaways. More colour. The book opens up and starts showing its work.' },
  { n: 3, name: 'Perceptual expansion', ground: 'var(--paper-deep)',  cue: 'Deeper contrast, spectral colour, larger spreads, bolder type, layered image systems. The most adventurous zone.' },
  { n: 4, name: 'Return · integration', ground: 'var(--paper)',       cue: 'Less density, calmer pages, fewer overlays, warmer tones, emotionally direct photography. The exhale.' },
];

const SPECTRUM = [
  ['Warm paper', '--paper'], ['Bone', '--bone'], ['Charcoal', '--ink'],
  ['Moss', '--moss'], ['Algae', '--algae'], ['Lake', '--lake'],
  ['Oxidised rust', '--rust'], ['Amber', '--amber'], ['Bioluminescent teal', '--biolume'],
  ['Ultraviolet', '--ultraviolet'], ['Coral', '--coral'], ['Signal orange', '--signal'],
  ['Acid', '--acid'],
];

function directionDoc(book) {
  const pg = (side, act, body) =>
    `<section class="page page--${side} act-${act} dir" data-side="${side}" data-spread="direction" data-label="direction">${body}</section>`;

  const actRow = (a) => `
    <div class="dir-act act-${a.n}">
      <div class="dir-act__chip" style="background:${a.ground}"><span>${a.n}</span></div>
      <div class="dir-act__body">
        <p class="label"><b>Act ${a.n}</b> ${esc(a.name)}</p>
        <p class="caption">${esc(a.cue)}</p>
        <div class="dir-act__accents">
          <i style="background:var(--accent-1)"></i>
          <i style="background:var(--accent-2)"></i>
          <i style="background:var(--accent-3)"></i>
        </div>
      </div>
    </div>`;

  const pages = [
    pg('verso', 1, `
      <div class="page__block dir-open">
        <p class="label"><b>Art direction</b> locked</p>
        <h1 class="essay-title">Field Notes &amp;<br>Hidden Systems</h1>
        <p class="deck">A 300 mm square hardcover that begins as a quiet observational field
          journal and opens, act by act, into a vivid exploration of hidden systems, perception
          and ordinary life.</p>
        <p class="specimen">Natural-history elegance · editorial collage · spectral, ecological
          and microscopic colour. Handmade, curious, alive. Never corporate, never cliché.</p>
      </div>`),

    pg('recto', 1, `
      <div class="page__block dir-block">
        <p class="label"><b>Fig. 1</b> The progression</p>
        <div class="dir-acts">${ACTS.map(actRow).join('')}</div>
        <p class="specimen dir-foot">An act is declared once, on a section or an essay.
          Every page inside it inherits its ground, its three accents and how dense the
          annotation layer may become.</p>
      </div>`),

    pg('verso', 2, `
      <div class="page__block dir-block">
        <p class="label"><b>Fig. 2</b> The spectrum</p>
        <div class="dir-spectrum">
          ${SPECTRUM.map(([name, v]) => `
            <div class="dir-swatch">
              <div class="dir-swatch__field" style="background:var(${v})"></div>
              <p class="specimen">${esc(name)}</p>
            </div>`).join('')}
        </div>
        <p class="specimen dir-foot">Not a rainbow. The colour system of stained slides, algae
          blooms, topographic and thermal charts, old field guides and risograph overprints.
          Which accents are in play is decided by the act, never by the spread.</p>
      </div>`),

    pg('recto', 2, `
      <div class="page__block dir-block">
        <p class="label"><b>Fig. 3</b> Three voices, and the hand</p>
        <div class="dir-voice">
          <p class="specimen">One · display serif</p>
          <p class="essay-title" style="font-size:34pt">The Ground Is Alive</p>
        </div>
        <div class="dir-voice">
          <p class="specimen">Two · text sans</p>
          <p class="prose" style="font-size:12pt;max-width:118mm">Body copy, captions, folios.
            It carries the reading and gets out of the way, which is the whole job.</p>
        </div>
        <div class="dir-voice">
          <p class="specimen">Three · systems voice</p>
          <p class="label"><b>Plate 14</b> Root network, 1:4</p>
          <p class="marginalia">Marginalia sits in the margin and stays there. It is a hand,
            not a second column.</p>
          <p class="specimen">Specimen 0114 · <span class="struck">overprint</span> · index<span class="index-mark">7</span></p>
        </div>
        <p class="specimen dir-foot">Named families in the brief are licensed. These are
          substitutes; all three swap in <b>tokens.css</b> and nowhere else.</p>
      </div>`),
  ];

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Art direction — Field Notes &amp; Hidden Systems</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<link rel="stylesheet" href="styles/preview.css">
</head>
<body class="preview is-proof-screen">
${pages.join('\n')}
<script src="scripts/preview.js"></script>
</body></html>
`;
}

/* ---- Type tester ---------------------------------------------------------
   The same specimen in every candidate stack, at true trim width. Families
   that are not installed are detected and flagged, so activating a family
   locally — Adobe Fonts, Monotype, a Fontstand trial — makes it render here
   immediately with no code change. */

function typeDoc(book) {
  const { stacks } = json('content/type-candidates.json');
  /* Family names carry double quotes; an inline style attribute is delimited by
     them, so swap to single quotes or the attribute terminates early and the
     whole stack silently falls back. */
  const q = (stack) => String(stack).replace(/"/g, "'");
  const specimen = (s, i) => `
    <section class="page page--recto stage-1 typespec" data-side="recto"
             data-spread="type specimen" data-label="${esc(s.name)}"
             style="--font-display:${q(s.display)};--font-text:${q(s.text)};--font-note:${q(s.note)};--font-hand:${q(s.hand)}">
      <div class="page__block">
        <div class="typespec__head">
          <p class="label"><b>${String(i + 1).padStart(2, '0')}</b> ${esc(s.name)}</p>
          <p class="specimen typespec__source">${esc(s.source)}</p>
          <p class="specimen typespec__probe" data-probe='${JSON.stringify(s.have)}'></p>
        </div>
        <h2 class="essay-title">Most of Life Is a Tuesday</h2>
        <p class="deck">Almost everything happens between the moments we think are important.</p>
        <div class="prose prose--cols prose--drop typespec__body">
          <p>Most of life does not happen during the big moments. It happens in between
          them. Not at the wedding, but on a Tuesday night years later when you are both
          tired and deciding what to eat. Not on the vacation, but while making coffee
          before work. Not at the graduation, but during the thousands of ordinary
          mornings that follow.</p>
          <p>We organise our memories around events. Birthdays, trips, weddings, new
          jobs, moves, achievements. These become the chapter headings. But chapter
          headings are not the book — the book is everything that happens between them.</p>
          <p>If you live for eighty years, only a tiny fraction of that time will contain
          anything you would call extraordinary. Most mornings will be ordinary mornings.
          Most dinners will not be memorable. That can sound disappointing, until you
          realise what it means: if happiness requires extraordinary circumstances then
          happiness is necessarily rare, but if ordinary experience can become meaningful,
          almost your entire life becomes available.</p>
        </div>
        <div class="typespec__foot">
          <p class="label"><b>Plate 14</b> Root network, 1:4</p>
          <p class="specimen">SPECIMEN 0114 · MAG 400X · 06.12.24 09:48</p>
          <p class="hand">wind off the lake, geese heading north</p>
        </div>
      </div>
    </section>`;

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Type tester — ${esc(book.title)}</title>
${['geometry.css', ...STYLES].map((h) => `<link rel="stylesheet" href="${h}">`).join('\n')}
<link rel="stylesheet" href="styles/preview.css">
</head>
<body class="preview is-proof-screen">
${stacks.map(specimen).join('\n')}
<script>
  /* document.fonts.check() is not an availability test — it reports true when
     the browser can fall back, which is always. Measure instead: set the same
     string in the candidate stack and in the bare fallback, and compare widths.
     Identical widths mean the family never loaded. */
  (function () {
    const probe = document.createElement('span');
    probe.textContent = 'Handgloves 0123456789 mmmiiiwww';
    probe.style.cssText = 'position:absolute;left:-9999px;top:0;font-size:96px;white-space:nowrap;';
    document.body.appendChild(probe);

    const widthIn = (stack) => { probe.style.fontFamily = stack; return probe.offsetWidth; };

    const run = () => {
      const bases = { monospace: widthIn('monospace'), serif: widthIn('serif'), 'sans-serif': widthIn('sans-serif') };
      document.querySelectorAll('[data-probe]').forEach((el) => {
        const missing = JSON.parse(el.dataset.probe).filter((f) =>
          Object.entries(bases).every(([base, w]) => widthIn('"' + f + '",' + base) === w));
        el.textContent = missing.length ? 'not installed — ' + missing.join(', ') : 'all families present';
        el.classList.add(missing.length ? 'is-missing' : 'is-present');
      });
      probe.remove();
    };

    /* A declared @font-face is only fetched when something uses it, so ask for
       every probed family at the probe's own size before measuring — otherwise
       a font that is present but not yet loaded reads as missing. */
    const families = [...document.querySelectorAll('[data-probe]')]
      .flatMap((el) => JSON.parse(el.dataset.probe));
    const warm = () => Promise.all(
      families.map((f) => document.fonts.load('96px \"' + f + '\"').catch(() => {})));

    if (document.fonts && document.fonts.ready) document.fonts.ready.then(warm).then(run);
    else window.addEventListener('load', run);
  })();
</script>
<script src="scripts/preview.js"></script>
</body></html>
`;
}

/* ---- Image manifest ------------------------------------------------------ */

function writeManifest() {
  const { images } = json('content/images.json');
  const row = (i) => [
    i.id, i.essay, i.section, i.spread, i.kind, i.subject, i.concept, i.purpose,
    i.aspect, i.target, i.filename, i.status, i.selection, i.revision || '—',
  ].map((c) => String(c).replace(/\|/g, '\\|')).join(' | ');

  const body = `<!-- GENERATED from content/images.json by \`npm run build\`. Edit the JSON, not this file. -->

# Image manifest

One row per planned image. Status moves \`not generated\` → \`generated\` → \`selected\`.
A file dropped into \`public/images/<kind>/<filename>\` replaces its placeholder plate on
the next build, so the proof PDF always shows exactly what has and has not been made.

| ID | Essay | Section | Spread | Type | Subject | Concept | Narrative purpose | Aspect | Target | Filename | Status | Selected | Revision notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${images.map((i) => `| ${row(i)} |`).join('\n')}

## Resolution rules

- Full single-page image: **4000 × 4000 px** minimum at 300 × 300 mm trim.
- Full two-page spread: **8000 × 4000 px** minimum.
- Always keep the largest clean original. Never upscale a weak generation to hit a number.
- Any full-bleed image must carry ${geometry.bleed} mm of expendable material on every trimmed edge.
`;
  fs.writeFileSync(path.join(root, 'prompts/image-manifest.md'), body);
}

/* ---- Fonts ---------------------------------------------------------------
   Self-hosted from npm rather than linked from a CDN, so the PDF build is
   reproducible offline and the exported file embeds exactly these faces.
   All four are open licence (OFL). See README > Typography for what they
   stand in for. */

const FONTS = [
  /* Static instances, not the variable file. Chromium emits variable-font
     instances into PDF as Type 3 glyph procedures, which prepress tools cannot
     subset and some presses reject outright. Statics embed as real CID
     TrueType outlines. Verified with `pdffonts`. */
  { file: '@fontsource/fraunces/files/fraunces-latin-400-normal.woff2',
    family: 'Fraunces', weight: '400', style: 'normal' },
  { file: '@fontsource/fraunces/files/fraunces-latin-400-italic.woff2',
    family: 'Fraunces', weight: '400', style: 'italic' },
  { file: '@fontsource/fraunces/files/fraunces-latin-600-normal.woff2',
    family: 'Fraunces', weight: '600', style: 'normal' },
  { file: '@fontsource/fraunces/files/fraunces-latin-700-normal.woff2',
    family: 'Fraunces', weight: '700', style: 'normal' },
  /* Hanken Grotesk — the body voice from 20 Aug 2026. The warmest of the four
     candidates, chosen for exactly that: humanist skeleton, calligraphic
     residue in the letterforms. Familjen moves down to the candidates so the
     comparison stays runnable in the type tester. */
  { file: '@fontsource/hanken-grotesk/files/hanken-grotesk-latin-400-normal.woff2',
    family: 'Hanken Grotesk', weight: '400', style: 'normal' },
  { file: '@fontsource/hanken-grotesk/files/hanken-grotesk-latin-400-italic.woff2',
    family: 'Hanken Grotesk', weight: '400', style: 'italic' },
  { file: '@fontsource/hanken-grotesk/files/hanken-grotesk-latin-500-normal.woff2',
    family: 'Hanken Grotesk', weight: '500', style: 'normal' },
  { file: '@fontsource/hanken-grotesk/files/hanken-grotesk-latin-600-normal.woff2',
    family: 'Hanken Grotesk', weight: '600', style: 'normal' },
  { file: '@fontsource/hanken-grotesk/files/hanken-grotesk-latin-700-normal.woff2',
    family: 'Hanken Grotesk', weight: '700', style: 'normal' },
  { file: '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
    family: 'IBM Plex Mono', weight: '400', style: 'normal' },
  { file: '@fontsource/caveat/files/caveat-latin-500-normal.woff2',
    family: 'Caveat', weight: '500', style: 'normal' },
];

/* Body-face candidates, loaded for the type tester only so they can be judged
   at trim size against real copy rather than from a specimen card. Static
   instances, for the same reason as everything else here: a variable instance
   is written into the PDF as Type 3 glyph procedures. Delete the ones that lose. */
const CANDIDATES = ['archivo', 'schibsted-grotesk', 'familjen-grotesk', 'epilogue']
  .flatMap((name) => [
    ['400', 'normal'], ['400', 'italic'], ['500', 'normal'], ['600', 'normal'],
  ].map(([weight, style]) => ({
    file: `@fontsource/${name}/files/${name}-latin-${weight}-${style}.woff2`,
    family: name.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' '),
    weight, style,
  })));

/* Licensed faces live outside the repo in fonts-licensed/ and are never
   committed — the Plattner Type EULA prohibits redistribution and prohibits
   serving the desktop OTFs from a website, and this repo is public. When the
   directory is present the build uses them; when it is not (CI, a fresh
   clone, the Pages deploy) the book falls back to the open-licence faces and
   says so. See LICENSING.md. */
const LICENSED = [
  { dir: 'falutin', file: 'FalutinTitle-Thin.otf',     family: 'Falutin Title', weight: '100' },
  { dir: 'falutin', file: 'FalutinTitle-Light.otf',    family: 'Falutin Title', weight: '300' },
  { dir: 'falutin', file: 'FalutinTitle-Regular.otf',  family: 'Falutin Title', weight: '400' },
  { dir: 'falutin', file: 'FalutinTitle-Medium.otf',   family: 'Falutin Title', weight: '500' },
  { dir: 'falutin', file: 'FalutinTitle-SemiBold.otf', family: 'Falutin Title', weight: '600' },
  { dir: 'falutin', file: 'FalutinTitle-Bold.otf',     family: 'Falutin Title', weight: '700' },
  { dir: 'falutin', file: 'FalutinTitle-Ultra.otf',    family: 'Falutin Title', weight: '900' },
];

async function installLicensedFonts(out) {
  const dir = path.join(out, 'fonts');
  let css = '';
  let found = 0;
  let woff2;
  try { woff2 = (await import('wawoff2')).default ?? (await import('wawoff2')); } catch { woff2 = null; }
  const cacheDir = path.join(root, 'fonts-licensed', '.ttf-cache');
  let warnedCff = false;

  for (const f of LICENSED) {
    const src = path.join(root, 'fonts-licensed', f.dir, f.file);
    if (!fs.existsSync(src)) continue;

    /* These are CFF (PostScript) outlines, and Chromium degrades a CFF face to
       Type 3 glyph procedures on the print path — prepress cannot subset those
       and some presses reject them outright. Repacking as WOFF2 does not help;
       the container is not the problem. Converting the outlines to TrueType
       does, and then it embeds as a real CID font. Verified with `pdffonts`.
       Conversion is cu2qu at 1/1000 em — the same path used to build variable
       TTFs from PostScript sources, and visually indistinguishable. */
    const ttf = path.join(cacheDir, f.file.replace(/\.otf$/i, '.ttf'));
    let name = f.file;
    if (fs.existsSync(ttf) && woff2) {
      const packed = await woff2.compress(fs.readFileSync(ttf));
      name = f.file.replace(/\.otf$/i, '.woff2');
      fs.writeFileSync(path.join(dir, name), Buffer.from(packed));
    } else {
      fs.copyFileSync(src, path.join(dir, name));
      if (!warnedCff) {
        console.warn('  ! shipping raw CFF — it will embed as Type 3 and prepress cannot subset it.');
        console.warn('    Run: npm run fonts:convert');
        warnedCff = true;
      }
    }

    css += `@font-face {
  font-family: "${f.family}";
  src: url("fonts/${name}") format("${name.endsWith('.woff2') ? 'woff2' : 'opentype'}");
  font-weight: ${f.weight};
  font-style: normal;
  font-display: block;
}\n`;
    found += 1;
  }
  return { css, found };
}

async function installFonts(out) {
  const dir = path.join(out, 'fonts');
  fs.mkdirSync(dir, { recursive: true });
  let css = '/* GENERATED by scripts/build.mjs. Faces are vendored from npm. */\n';
  for (const f of FONTS) {
    const src = path.join(root, 'node_modules', f.file);
    const name = path.basename(f.file);
    if (!fs.existsSync(src)) { console.warn(`  ! missing font ${f.file}`); continue; }
    fs.copyFileSync(src, path.join(dir, name));
    css += `@font-face {
  font-family: "${f.family}";
  src: url("fonts/${name}") format("woff2");
  font-weight: ${f.weight};
  font-style: ${f.style};
  font-display: block;
}\n`;
  }

  for (const f of CANDIDATES) {
    const src = path.join(root, 'node_modules', f.file);
    if (!fs.existsSync(src)) continue;
    const name = path.basename(f.file);
    fs.copyFileSync(src, path.join(dir, name));
    css += `@font-face {
  font-family: "${f.family}";
  src: url("fonts/${name}") format("woff2");
  font-weight: ${f.weight};
  font-style: ${f.style};
  font-display: block;
}\n`;
  }

  const licensed = await installLicensedFonts(out);
  css += licensed.css;
  /* The display voice resolves to the licensed face when it is here and to the
     open-licence one when it is not, so the book builds either way. */
  css += `\n:root { --display-family: ${licensed.found
    ? '"Falutin Title", "Fraunces", "Hoefler Text", serif'
    : '"Fraunces", "Hoefler Text", serif'}; }\n`;

  fs.writeFileSync(path.join(out, 'fonts.css'), css);
  return licensed.found;
}

/* ---- Assets -------------------------------------------------------------- */

function copyDir(from, to) {
  if (!fs.existsSync(from)) return;
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

/**
 * Copy `public/` into the build.
 *
 * A web build swaps the press masters for the committed derivatives in
 * `public/images-web` (see `npm run derive`). It must SKIP `public/images`
 * entirely rather than copy it and overwrite: on a checkout that did not fetch
 * LFS the masters are pointer files, and any master without a derivative would
 * otherwise survive into build/ as a 130-byte text file pretending to be a
 * picture. A missing image draws a labelled plate and is obvious; a pointer
 * file draws nothing and is not.
 */
function copyAssets(out) {
  const pub = path.join(root, 'public');

  /* `images-web` is never copied under its own name. It is the source for a web
     build's `images`, and in a press build it is not wanted at all — shipping it
     verbatim would put a second, redundant copy of every picture in build/. */
  for (const entry of fs.readdirSync(pub, { withFileTypes: true })) {
    if (entry.name === 'images-web') continue;
    if (entry.name === 'images' && web) continue;
    const s = path.join(pub, entry.name);
    const d = path.join(out, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }

  if (!web) return;

  const derived = path.join(pub, 'images-web');
  if (!fs.existsSync(derived)) {
    throw new Error('BOOK_WEB=1 but public/images-web does not exist — run `npm run derive`.');
  }
  /* Replace rather than merge: a leftover master from an earlier press build
     would otherwise survive into the deployed site at full resolution. */
  fs.rmSync(path.join(out, 'images'), { recursive: true, force: true });
  copyDir(derived, path.join(out, 'images'));
}

/* ---- Build --------------------------------------------------------------- */

export async function build() {
  const book = json('content/book.json');
  const toc = json('content/contents.json');
  const out = path.join(root, 'build');

  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, 'geometry.css'), geometryCss());
  const licensedCount = await installFonts(out);
  copyDir(path.join(root, 'src/styles'), path.join(out, 'styles'));
  copyDir(path.join(root, 'src/scripts'), path.join(out, 'scripts'));
  copyAssets(out);

  const { openings } = compose(book, toc);            // pass 1: find the folios
  const { pages, count } = compose(book, toc, openings); // pass 2: print them
  const body = pages.join('\n');

  fs.writeFileSync(path.join(out, 'book.html'),
    document_({ title: `${book.title} — ${book.author}`, body, preview: false }));
  fs.writeFileSync(path.join(out, 'preview.html'),
    document_({ title: `${book.title} — preview`, body, preview: true }));
  fs.writeFileSync(path.join(out, 'cover-wrap.html'), coverWrapDoc(book));
  const covers = coverOptionsDoc(book);
  fs.writeFileSync(path.join(out, 'cover-options.html'), covers.screen);
  fs.writeFileSync(path.join(out, 'cover-options-print.html'), covers.print);
  fs.writeFileSync(path.join(out, 'direction.html'), directionDoc(book));
  fs.writeFileSync(path.join(out, 'type.html'), typeDoc(book));
  fs.writeFileSync(path.join(out, 'index.html'), indexDoc(book, count));
  writeManifest();

  const sheets = Math.ceil(count / 2);
  console.log(
    licensedCount
      ? `  display voice: Falutin Title (${licensedCount} weights, licensed — not in this repo)`
      : `  display voice: Fraunces (licensed faces absent; drop them in fonts-licensed/)`
  );
  console.log(
    `✓ ${count} interior pages (${sheets} leaves) + 2 cover surfaces` +
    `  ·  ${press ? 'PRESS: bleed + crop marks' : 'proof: trimmed, no marks'}` +
    `  ·  spine ${spineWidth()} mm (provisional)`
  );
}

await build();

if (process.argv.includes('--watch')) {
  const { default: chokidar } = await import('chokidar');
  chokidar
    .watch(['content', 'src', 'public', 'book.config.js'], { cwd: root, ignoreInitial: true })
    .on('all', () => {
      build().catch((e) => console.error('✗', e.message));
    });
  console.log('watching content/ src/ public/ …');
}
