#!/usr/bin/env node
/* Regenerate the attribution list from the manifest. Any image carrying an
   `origin: archive` gets a credit line; anything missing source or licence is
   flagged loudly, because that is the kind of gap that surfaces at press.

   This file is the working record of provenance for everything the project
   holds, so it lists sourced images whether or not they are currently in the
   book — knowing where a cut asset came from still matters if it returns. The
   entries that are NOT in the book are marked, because the printed imprint
   credits only what the object contains and the two lists must be readable
   against each other. The imprint derives its own lines from the composed HTML;
   see the note on L.imprint. */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { images } = JSON.parse(fs.readFileSync(path.join(root, 'content/images.json'), 'utf8'));

const sourced = images.filter((i) => i.origin === 'archive');
const gaps = sourced.filter((i) => !i.source || !i.license);
const cut = (i) => String(i.spread || '').startsWith('Unplaced');

const body = `<!-- GENERATED by \`npm run credits\` from content/images.json. -->

# Credits and permissions

${sourced.length ? '' : '_No sourced material yet._\n'}
${sourced.map((i) => `- **${i.id}**${cut(i) ? ' _(not in the book — no printed credit)_' : ''} — ` +
  `${i.credit || '_credit missing_'}. ` +
  `Source: ${i.source || '_missing_'}. Licence: ${i.license || '_missing_'}.`).join('\n')}

## Generated and original material

${images.filter((i) => i.origin !== 'archive').length} images in this book are
generated or original and need no third-party attribution. Original diagrams are
drawn in code — see \`src/layouts/diagrams.mjs\`.

${gaps.length ? `## ⚠ Incomplete\n\n${gaps.map((i) => `- ${i.id}`).join('\n')}\n\nEvery sourced asset needs \`source\` and \`license\` before this book goes to press.\n` : ''}`;

fs.writeFileSync(path.join(root, 'content/plan/credits.md'), body);
const notInBook = sourced.filter(cut).length;
console.log(`✓ ${sourced.length} sourced (${sourced.length - notInBook} printed, ${notInBook} not in the book), `
  + `${gaps.length} incomplete → content/plan/credits.md`);
