#!/usr/bin/env node
/* Regenerate the attribution list from the manifest. Any image carrying an
   `origin: archive` gets a credit line; anything missing source or licence is
   flagged loudly, because that is the kind of gap that surfaces at press. */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { images } = JSON.parse(fs.readFileSync(path.join(root, 'content/images.json'), 'utf8'));

const sourced = images.filter((i) => i.origin === 'archive');
const gaps = sourced.filter((i) => !i.source || !i.license);

const body = `<!-- GENERATED by \`npm run credits\` from content/images.json. -->

# Credits and permissions

${sourced.length ? '' : '_No sourced material yet._\n'}
${sourced.map((i) => `- **${i.id}** — ${i.credit || '_credit missing_'}. ` +
  `Source: ${i.source || '_missing_'}. Licence: ${i.license || '_missing_'}.`).join('\n')}

## Generated and original material

${images.filter((i) => i.origin !== 'archive').length} images in this book are
generated or original and need no third-party attribution. Original diagrams are
drawn in code — see \`src/layouts/diagrams.mjs\`.

${gaps.length ? `## ⚠ Incomplete\n\n${gaps.map((i) => `- ${i.id}`).join('\n')}\n\nEvery sourced asset needs \`source\` and \`license\` before this book goes to press.\n` : ''}`;

fs.writeFileSync(path.join(root, 'content/plan/credits.md'), body);
console.log(`✓ ${sourced.length} sourced, ${gaps.length} incomplete → content/plan/credits.md`);
