/* Writes one self-contained, paste-ready drafting prompt per unwritten essay.
   The brief is the single source; this only fills in the essay's own values, so
   editing content/plan/drafting-brief.md still changes all six. */
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const brief = fs.readFileSync(path.join(root, 'content/plan/drafting-brief.md'), 'utf8');

/* Everything after the rule that closes the brief's own preamble. Split on the
   FIRST rule only: the format example further down is YAML frontmatter and its
   own `---` fences would otherwise cut the prompt off before it. */
const body = brief.slice(brief.indexOf('\n---\n') + 5).trimStart();

const ESSAYS = [
  { n: '03', id: 'systems-nobody-designed', title: 'The Beauty of Systems Nobody Designed', part: 'II', partTitle: 'What Are We?', stage: 2, ground: 'ground-03-local-rules-flocking' },
  { n: '04', id: 'intelligence-outside', title: 'The Intelligence Outside Your Head', part: 'II', partTitle: 'What Are We?', stage: 2, ground: 'ground-04-extended-cognition' },
  { n: '05', id: 'strange-privilege', title: 'The Strange Privilege of Being Alive During a Technological Revolution', part: 'III', partTitle: 'The World Is Changing', stage: 3, ground: 'ground-05-imagine-to-make' },
  { n: '06', id: 'before-time', title: 'The Last Generation That Remembers the Before-Time', part: 'III', partTitle: 'The World Is Changing', stage: 4, ground: 'ground-06-density-thinning' },
  { n: '07', id: 'pilgrimages', title: 'Why Humans Need Pilgrimages', part: 'IV', partTitle: 'While We’re Here', stage: 5, ground: 'ground-07-convergent-routes' },
  { n: '08', id: 'while-were-here', title: 'While We’re Here', part: 'IV', partTitle: 'While We’re Here', stage: 5, ground: 'ground-08-nested-systems' },
];

const STAGE_NOTE = {
  2: 'Stage II, "notice the patterns". Bone ground, still light. Denser than Part I but not yet dark.',
  3: 'Stage III, "enter the systems". **The page inverts to a charcoal ground and the type reverses out.** Write knowing the reader is inside something rather than looking at it.',
  4: 'Stage IV, "expand awareness". **A dark ground, and the most vivid pages in the book.** This is the peak of the arc, so it is the one essay allowed to be the loudest.',
  5: 'Stage V, "return with wonder". Warm paper again, calmer, fewer elements. It has to earn its quiet by following the dark pages, not by avoiding what they said.',
};

const dir = path.join(root, 'prompts/essays');
fs.rmSync(dir, { recursive: true, force: true });
fs.mkdirSync(dir, { recursive: true });

for (const e of ESSAYS) {
  const filled = body
    .replace(
      '**The essay you are drafting is: [TITLE], in Part [N].**',
      `**The essay you are drafting is: ${e.title}, in Part ${e.part}, ${e.partTitle}.**\n\n${STAGE_NOTE[e.stage]}`,
    )
    .replace(
      /id: short-slug\nnumber: "04"\npart: II\nstage: 2\npartTitle: What Are We\?\ntitle: The Full Title of the Essay/,
      `id: ${e.id}\nnumber: "${e.n}"\npart: ${e.part}\nstage: ${e.stage}\npartTitle: ${e.partTitle}\ntitle: ${e.title}`,
    );

  const out = `<!-- GENERATED by \`npm run draft\`. Edit content/plan/drafting-brief.md, not this file. -->

# Essay ${e.n} — ${e.title}

Paste everything inside the block into ChatGPT. Nothing else is needed; it is
written to stand alone, because ChatGPT cannot see this repo.

When the draft comes back, save it as \`content/essays/${e.id}.md\`, add it to
\`sequence\` in \`content/book.json\`, and run \`npm run dev\`. Spread types are
assigned here, not by ChatGPT. The ground illustration keyed to this essay is
\`${e.ground}\` — see \`prompts/outstanding-brief.md\`.

\`\`\`\`text
${filled}
\`\`\`\`
`;

  fs.writeFileSync(path.join(dir, `${e.n}-${e.id}.md`), out);
}

console.log(`✓ ${ESSAYS.length} drafting prompts → prompts/essays/`);
