#!/usr/bin/env node
/* Validate content/facts.json and regenerate the sources page.

   The book's authority rests on its numbers being checkable, so a claim without
   a source is treated the same way as an image without a licence: a gap that
   has to surface now rather than at press. Run bare to check and regenerate;
   `--strict` exits non-zero if anything is unverified, which is what a release
   build should use. */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { facts } = JSON.parse(fs.readFileSync(path.join(root, 'content/facts.json'), 'utf8'));

const strict = process.argv.includes('--strict');
const verified = facts.filter((f) => f.status === 'verified');
const pending = facts.filter((f) => f.status === 'unverified' || f.status === 'disputed');

/* A fact claiming to be verified but carrying no source is worse than an
   unverified one, because it looks settled. Fail on it either way. */
const lying = verified.filter((f) => !f.source || !f.source.url);

const cite = (s) => [
  s.authors,
  `*${s.title}*`,
  s.publication,
  s.year,
].filter(Boolean).join('. ') + `. <${s.url}>`;

const body = `<!-- GENERATED by \`npm run facts\` from content/facts.json. Do not edit. -->

# Sources and notes

Every technical number in this book is listed here with the source it came from.
Where a figure is contested, small-sample or easy to misstate, the note says so.

${verified.length} verified · ${pending.length} outstanding

---

${verified.map((f) => `### ${f.claim}

${cite(f.source)}

${f.note ? `**Note.** ${f.note}\n` : ''}${f.replaces ? `**Replaces.** ${f.replaces}\n` : ''}
*Used in ${f.usedIn.join('; ')}.*
`).join('\n---\n\n')}

${pending.length ? `---

## Outstanding

These are not settled and must not appear on a page until they are.

${pending.map((f) => `- **${f.id}** (${f.status}) — ${f.claim}${f.note ? `\n  ${f.note}` : ''}`).join('\n')}
` : ''}`;

fs.writeFileSync(path.join(root, 'content/plan/sources.md'), body);

for (const f of lying) console.error(`✗ ${f.id} is marked verified but has no source URL`);
for (const f of pending) console.warn(`⚠ ${f.id} — ${f.status}, not safe to set`);
console.log(`${verified.length} verified, ${pending.length} outstanding → content/plan/sources.md`);

if (lying.length) process.exit(1);
if (strict && pending.length) {
  console.error('✗ --strict: every claim must be verified before press');
  process.exit(1);
}
