#!/usr/bin/env node
/* Rebuild `fonts-cjk/` — the Noto subsets that carry the characters no Latin
 * face in the book can set.
 *
 *   npm run fonts:cjk
 *
 * Reads the composed pages in `build/`, works out which characters need Noto,
 * and copies the few subset files that carry them out of the fontsource
 * packages. The result is committed; see scripts/lib/cjk.mjs for why.
 *
 * The packages are NOT a dependency of this project — they are 130 MB and every
 * `npm ci` on the Pages runner would pay for them. Install them when you need
 * to run this, and remove them again:
 *
 *   npm i --no-save @fontsource/noto-sans-jp @fontsource/noto-sans-kr
 *   npm run fonts:cjk
 *
 * Run it when the book gains a character the current subsets do not cover —
 * `npm run build` says so, by name, when that happens.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

import { DIR, MANIFEST, FAMILIES, unlatinChars, subsetsOf, carries } from './lib/cjk.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const out = path.join(root, DIR);

const built = path.join(root, 'build');
const pages = fs.existsSync(built) ? fs.readdirSync(built).filter((f) => f.endsWith('.html')) : [];
if (!pages.length) {
  console.error('✗ No composed pages in build/ — run `npm run build` first.');
  process.exit(1);
}

const need = unlatinChars(pages.map((f) => fs.readFileSync(path.join(built, f), 'utf8')).join('\n'));
if (!need.size) {
  console.log('✓ The book prints nothing the Latin faces cannot set — no subsets needed.');
  process.exit(0);
}

/* Each family is asked only for what is still uncovered, so KR contributes
   Hangul and not a second copy of the ideographs JP already answered for. */
const covered = new Set();
const chosen = [];
const sources = [];

for (const { spec, family } of FAMILIES) {
  let cssFile;
  try { cssFile = require.resolve(spec); } catch {
    console.error(`✗ ${spec.split('/').slice(0, 2).join('/')} is not installed.`);
    console.error('  npm i --no-save @fontsource/noto-sans-jp @fontsource/noto-sans-kr');
    process.exit(1);
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(path.dirname(cssFile), 'package.json'), 'utf8'));
  sources.push(`${pkg.name}@${pkg.version}`);

  const outstanding = [...need].filter((c) => !covered.has(c));
  if (!outstanding.length) continue;

  for (const sub of subsetsOf(cssFile)) {
    const takes = outstanding.filter((c) => carries(sub.ranges, c));
    if (!takes.length) continue;
    const from = path.join(path.dirname(cssFile), 'files', sub.file);
    if (!fs.existsSync(from)) continue;
    chosen.push({ file: sub.file, family, range: sub.range, from });
    for (const c of takes) covered.add(c);
  }
}

/* Written fresh each time: a subset that is no longer needed should stop being
   committed, not linger because nothing removed it. */
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

let bytes = 0;
for (const c of chosen) {
  fs.copyFileSync(c.from, path.join(out, c.file));
  bytes += fs.statSync(c.from).size;
}

/* The OFL requires the licence travel with the fonts. Both families carry the
   same text, so one copy answers for both. */
const licence = path.join(path.dirname(require.resolve(FAMILIES[0].spec)), 'LICENSE');
if (fs.existsSync(licence)) fs.copyFileSync(licence, path.join(out, 'OFL.txt'));

fs.writeFileSync(path.join(out, MANIFEST), `${JSON.stringify({
  note: 'GENERATED by `npm run fonts:cjk`. Commit it. See scripts/lib/cjk.mjs.',
  sources,
  characters: [...covered].sort((a, b) => a - b).map((c) => `U+${c.toString(16).toUpperCase()}`),
  subsets: chosen.map(({ file, family, range }) => ({ file, family, range })),
}, null, 2)}\n`);

const orphans = [...need].filter((c) => !covered.has(c));
if (orphans.length) {
  console.warn(`  ! ${orphans.length} character${orphans.length === 1 ? '' : 's'} neither family covers:`);
  console.warn(`    ${orphans.map((c) => `U+${c.toString(16).toUpperCase()} ${String.fromCodePoint(c)}`).join('  ')}`);
}

console.log(`✓ ${chosen.length} subsets for ${covered.size} characters (${(bytes / 1024).toFixed(0)} KB) → ${DIR}/`);
console.log(`  from ${sources.join(', ')}`);
console.log('  commit it — the build reads these, not node_modules.');
