#!/usr/bin/env node
/* Generate copy-paste-ready image prompts from content/images.json.
   One self-contained prompt per image: no preamble to remember, no cross
   references to resolve. Paste a block, generate, save under the given
   filename, and the next build swaps out the placeholder plate. */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { images } = JSON.parse(fs.readFileSync(path.join(root, 'content/images.json'), 'utf8'));

const PHOTO_STYLE =
  'A believable documentary photograph of the real world — quiet, contemplative, ' +
  'observant, naturalistic, cinematic, very slightly uncanny. Natural available light ' +
  'only, late afternoon or early morning. Restrained composition with strong negative ' +
  'space and slightly imperfect, off-centre framing, as though the photographer did not ' +
  'have time to fix it. Believable lens behaviour: mild vignetting, real depth of field, ' +
  'no exaggerated bokeh. Muted colour — warm neutrals, faded blue, moss green, occasional ' +
  'amber light. Subtle 35 mm film grain and real surface texture. Emotionally present, ' +
  'never sentimental. Shot on a 35 mm or 50 mm prime.';

const PHOTO_AVOID =
  'Avoid: fantasy; neon, glow or bloom effects; floating or impossible objects; glossy ' +
  'commercial or stock photography; exaggerated HDR or heavy grading; smiling models; ' +
  'anyone looking into the lens; visible text, signage lettering, logos or watermarks; ' +
  'distorted hands, faces or anatomy; AI-render sheen; symmetrical dead-centre ' +
  'composition; added lens flare.';

const ILLO_STYLE =
  'An illustrated plate from a vintage scientific field guide, hand-drawn in ink on warm ' +
  'cream paper. Imperfect geometry — circles slightly out of true, lines drawn by hand, ' +
  'everything a degree or two off square. Field-guide illustration crossed with vintage ' +
  'scientific diagram, cartography and marginalia: arrows, rings, timelines, measure ' +
  'scales, tiny human figures. Screenprint and risograph texture with visible ink density ' +
  'variation and slight misregistration. Charcoal near-black ink on a warm cream ground ' +
  '(#F3EFE5), with restrained accents of muted rust (#A95738), faded cobalt (#536D8E) and ' +
  'moss green (#68735B). Intelligent, tactile, playful, handmade.';

const ILLO_AVOID =
  'Avoid: gradients; glossy 3D or rendered lighting; generic vector people; corporate ' +
  'infographic style; SaaS or explainer-video illustration; polished icon sets; ' +
  'decorative complexity with no conceptual purpose; fake handwritten paragraphs or ' +
  'invented lettering; any legible text; psychedelic imagery; symmetry for its own sake.';

const FRAME = {
  '1:1': 'Square frame (1:1).',
  '2:1': 'Wide panoramic frame (2:1). This runs across a two-page spread, so keep the centre calm and place nothing important in the middle 30 mm.',
  '3:1': 'Very wide band (3:1), figures small in the frame.',
  '2:3': 'Vertical frame (2:3), subject low, generous empty space above.',
  '3:2': 'Horizontal frame (3:2).',
  '4:3': 'Horizontal frame (4:3).',
  '3:4': 'Vertical frame (3:4).',
  '4:5': 'Vertical frame (4:5).',
};

const byEssay = new Map();
for (const i of images) {
  if (!byEssay.has(i.essay)) byEssay.set(i.essay, []);
  byEssay.get(i.essay).push(i);
}

const promptFor = (i) => {
  const style = i.kind === 'illustration' ? ILLO_STYLE : PHOTO_STYLE;
  const avoid = i.kind === 'illustration' ? ILLO_AVOID : PHOTO_AVOID;
  const frame = FRAME[i.aspect] || `Frame ${i.aspect}.`;
  return [style, i.subject, frame, avoid].join('\n\n');
};

let out = `<!-- GENERATED by \`npm run prompts\` from content/images.json. Edit the JSON. -->

# Image prompts

One self-contained block per image. Paste a block into ChatGPT, generate, then
save the result as the given filename under \`public/images/<type>/\`. The next
\`npm run build\` replaces the placeholder plate automatically — no code change.

Ask for the largest size the model will produce, then keep the original. Do not
upscale a weak generation to hit the target; regenerate instead.

`;

for (const [essay, list] of byEssay) {
  out += `\n---\n\n## ${essay}\n`;
  for (const i of list) {
    out += `\n### ${i.id}\n\n`;
    out += `**Save as** \`public/images/${i.kind}/${i.filename}\` · ${i.aspect} · target ${i.target}\n`;
    out += `**Where it goes** ${i.spread}\n`;
    out += `**Why it is there** ${i.purpose}\n`;
    if (i.revision) out += `**Watch for** ${i.revision}\n`;
    out += `\n\`\`\`text\n${promptFor(i)}\n\`\`\`\n`;
  }
}

fs.mkdirSync(path.join(root, 'prompts'), { recursive: true });
fs.writeFileSync(path.join(root, 'prompts/image-prompts.md'), out);
console.log(`✓ ${images.length} prompts → prompts/image-prompts.md`);
